### PR TITLE
Formatting, Hostage Regulations

### PR DESCRIPTION
**Pull request by lewisjph**
Some updates to the formatting of the Supreme Guidelines. This includes the removal of the RH Regulations due to the fact that they may be included in the Supreme Guidelines at a later date and are currently stored within a different document. In addition to this, a warning has been added to the Hostage Regulations which informs readers that the section has not yet been completed and is subject to updates. Other general formatting changes have been made, however are less notable than those listed.

### CODE REVIEW

**Review by FritzVohlkson — APPROVED** [review]

**Comment by Ulferno** [comment]
Should this exist? I don't see any directory named `red_heron_regulations`.
https://github.com/lewisjph/legislation/blob/master/sidebars.js#L66-L75

Should this be visible? I don't see any documentation regarding it.
https://github.com/lewisjph/legislation/blob/master/sidebars.js#L76-L85

**Review by Ulferno — CHANGES_REQUESTED** [review]
lgtm

**Review by Ulferno — DISMISSED** [review]
misclick

**Review by Ulferno — APPROVED** [review]
lgtm

**Review by FritzVohlkson — APPROVED** [review]

**Pull request merged**
